### ISSUE TITLE
Minor Mispelling on cryogenweb.org's 

### ISSUE THREAD

**Issue by gotwf** [cryogen-project/cryogen-docs#29]
Front door links:

s/Docsumentation/Documentation/

Peace.

**Comment by lacarmen** [comment]
Do you have css disabled or something? It's supposed to be "Docs" for mobile and "Documentation" on desktop. 

`Doc<span class="show-on-mobile">s</span><span class="hide-on-mobile">umentation</span>`

**Comment by gotwf** [comment]
Fixed now.   I scaled my browser window and the link title switches as appropriate.

 I did do a minor systems update yesterday that  included Firefox (presently using 74.0).    You changed nothing on your end?

Oh well, it's working now and I shall not look a git horse too closely in the mouth.

Thx o/

**Comment by gotwf** [comment]
Ah, yeah.. this occurs when using minimalist browsers.  Or emacs eww anyways, which is otherwise pretty sweet for browsing docs.  No adaptive js though.  Sorry about that.
